--- #YAML:1.0
name:                Curses-UI-POE
version:             0.034
abstract:            A subclass that forces Curses::UI to use POE
license:             ~
author:              
    - Scott S. McCoy (tag@cpan.org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Curses::UI:                    0.93
    POE:                           0.11
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
